version: '3.1'

services:
  seqservice:
    image: datalust/seq:latest
    environment:
     - SA_PASSWORD=Pass@word
     - ACCEPT_EULA=Y
    ports:
     - "5341:5341"
     - "8081:80"
    volumes:
     - ./logs/data:/data
  coveragepolygonservice:
    image: carlosdz97/coveragepolygon:latest
    ports: ["8080:80","1443:443"]
  geocodingservice:
    image: carlosdz97/geocoding:latest
    ports: ["8082:80","1444:443"]
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"
    volumes:
     - sqldata:/var/opt/mssql
volumes:
  sqldata:
    external: false